"""squashed_initial_schema

Revision ID: a2b4203413b8
Revises: 
Create Date: 2026-07-10 21:45:18.272353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b4203413b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_id'), 'audio_assets', ['id'], unique=False)
    op.create_table('grammar_points',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_points_id'), 'grammar_points', ['id'], unique=False)
    op.create_table('kanjis',
    sa.Column('character', sa.String(length=10), nullable=False),
    sa.Column('onyomi', sa.String(length=100), nullable=True),
    sa.Column('kunyomi', sa.String(length=100), nullable=True),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.Column('stroke_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kanjis_id'), 'kanjis', ['id'], unique=False)
    op.create_table('levels',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('target_level', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('level_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('job_type', sa.Enum('QUESTION_GENERATION', 'TTS_GENERATION', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('prompt_json', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_table('passwordresettokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresettokens_id'), 'passwordresettokens', ['id'], unique=False)
    op.create_index(op.f('ix_passwordresettokens_token_hash'), 'passwordresettokens', ['token_hash'], unique=True)
    op.create_table('refreshtokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtokens_id'), 'refreshtokens', ['id'], unique=False)
    op.create_index(op.f('ix_refreshtokens_token_hash'), 'refreshtokens', ['token_hash'], unique=True)
    op.create_table('user_masteries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill', sa.Enum('VOCABULARY', 'GRAMMAR', 'READING', 'LISTENING', name='skilltype'), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_masteries_id'), 'user_masteries', ['id'], unique=False)
    op.create_table('vocabularies',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('kana', sa.String(length=100), nullable=False),
    sa.Column('romaji', sa.String(length=100), nullable=True),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.Column('audio_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabularies_id'), 'vocabularies', ['id'], unique=False)
    op.create_table('example_sentences',
    sa.Column('japanese', sa.Text(), nullable=False),
    sa.Column('romaji', sa.Text(), nullable=True),
    sa.Column('indonesian', sa.Text(), nullable=False),
    sa.Column('audio_id', sa.String(length=36), nullable=True),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=True),
    sa.Column('grammar_point_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_sentences_id'), 'example_sentences', ['id'], unique=False)
    op.create_table('units',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.Enum('PRACTICE', 'EXAM', name='sessionmode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('answered_questions', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_id'), 'learning_sessions', ['id'], unique=False)
    op.create_table('lesson_grammar_points',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('grammar_point_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'grammar_point_id')
    )
    op.create_table('lesson_kanjis',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('kanji_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['kanji_id'], ['kanjis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'kanji_id')
    )
    op.create_table('lesson_sections',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_sections_id'), 'lesson_sections', ['id'], unique=False)
    op.create_table('lesson_vocabularies',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'vocabulary_id')
    )
    op.create_table('readings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('audio_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_table('user_lesson_progress',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='lessonstatus'), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('last_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lesson_progress_id'), 'user_lesson_progress', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('reading_id', sa.String(length=36), nullable=True),
    sa.Column('audio_asset_id', sa.String(length=36), nullable=True),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'MATCHING', 'ORDERING', 'CLOZE', 'LISTENING', 'READING', name='questiontype'), nullable=False),
    sa.Column('skill', sa.Enum('VOCABULARY', 'GRAMMAR', 'READING', 'LISTENING', name='skilltype'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('prompt_json', sa.Text(), nullable=False),
    sa.Column('answer_key_json', sa.Text(), nullable=True),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AUTO_VALIDATED', 'NEEDS_REVISION', 'APPROVED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='questionstatus'), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('xp_transactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_transactions_id'), 'xp_transactions', ['id'], unique=False)
    op.create_table('learning_session_questions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=True),
    sa.Column('user_answer_json', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_session_questions_id'), 'learning_session_questions', ['id'], unique=False)
    op.create_table('question_reviews',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('status_given', sa.Enum('DRAFT', 'AUTO_VALIDATED', 'NEEDS_REVISION', 'APPROVED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='questionstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_reviews_id'), 'question_reviews', ['id'], unique=False)
    op.create_table('review_schedules',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_schedules_id'), 'review_schedules', ['id'], unique=False)
    op.create_table('user_mistakes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mistakes_id'), 'user_mistakes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mistakes_id'), table_name='user_mistakes')
    op.drop_table('user_mistakes')
    op.drop_index(op.f('ix_review_schedules_id'), table_name='review_schedules')
    op.drop_table('review_schedules')
    op.drop_index(op.f('ix_question_reviews_id'), table_name='question_reviews')
    op.drop_table('question_reviews')
    op.drop_index(op.f('ix_learning_session_questions_id'), table_name='learning_session_questions')
    op.drop_table('learning_session_questions')
    op.drop_index(op.f('ix_xp_transactions_id'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_user_lesson_progress_id'), table_name='user_lesson_progress')
    op.drop_table('user_lesson_progress')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_table('lesson_vocabularies')
    op.drop_index(op.f('ix_lesson_sections_id'), table_name='lesson_sections')
    op.drop_table('lesson_sections')
    op.drop_table('lesson_kanjis')
    op.drop_table('lesson_grammar_points')
    op.drop_index(op.f('ix_learning_sessions_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_example_sentences_id'), table_name='example_sentences')
    op.drop_table('example_sentences')
    op.drop_index(op.f('ix_vocabularies_id'), table_name='vocabularies')
    op.drop_table('vocabularies')
    op.drop_index(op.f('ix_user_masteries_id'), table_name='user_masteries')
    op.drop_table('user_masteries')
    op.drop_index(op.f('ix_refreshtokens_token_hash'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_id'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    op.drop_index(op.f('ix_passwordresettokens_token_hash'), table_name='passwordresettokens')
    op.drop_index(op.f('ix_passwordresettokens_id'), table_name='passwordresettokens')
    op.drop_table('passwordresettokens')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_kanjis_id'), table_name='kanjis')
    op.drop_table('kanjis')
    op.drop_index(op.f('ix_grammar_points_id'), table_name='grammar_points')
    op.drop_table('grammar_points')
    op.drop_index(op.f('ix_audio_assets_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    # ### end Alembic commands ###
