"""Add question_revisions

Revision ID: 25c9cb6ccbe3
Revises: a2b4203413b8
Create Date: 2026-07-10 22:33:58.966213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25c9cb6ccbe3'
down_revision: Union[str, None] = 'a2b4203413b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_revisions',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('prompt_json', sa.JSON(), nullable=False),
    sa.Column('answer_key_json', sa.JSON(), nullable=True),
    sa.Column('explanation_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_revisions_id'), 'question_revisions', ['id'], unique=False)
    op.alter_column('questions', 'prompt_json',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('questions', 'answer_key_json',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('questions', 'explanation_json',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('LEARNER', 'CONTENT_EDITOR', 'REVIEWER', 'ADMINISTRATOR', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('LEARNER', 'CONTENT_EDITOR', 'REVIEWER', 'ADMINISTRATOR', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('questions', 'explanation_json',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('questions', 'answer_key_json',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('questions', 'prompt_json',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_question_revisions_id'), table_name='question_revisions')
    op.drop_table('question_revisions')
    # ### end Alembic commands ###
