import json
import time
from datetime import datetime, timezone
from typing import Any

from app.db.session import SessionLocal
from app.models.ai_jobs import GenerationJob, JobStatus
from app.models.curriculum import Lesson
from app.models.question import Question, QuestionStatus, QuestionType, SkillType
from app.services.ai_provider import get_ai_provider
from app.services.question_workflow import QuestionWorkflowError, snapshot_question, validate_question_payload
from app.worker import celery_app


def _job_config(job: GenerationJob) -> dict[str, Any]:
    try:
        payload = json.loads(job.prompt_json)
        return payload if isinstance(payload, dict) else {}
    except json.JSONDecodeError:
        return {"additional_notes": job.prompt_json}


def _coerce_prompt(raw: dict[str, Any]) -> dict[str, Any]:
    prompt = raw.get("prompt_json") or raw.get("prompt")
    if isinstance(prompt, dict):
        return prompt

    text = str(prompt or raw.get("text") or raw.get("question") or "Generated question")
    options = raw.get("options")
    if not isinstance(options, list) or not options:
        options = ["A", "B"]

    normalized_options = []
    for index, option in enumerate(options):
        if isinstance(option, dict):
            option_id = str(option.get("id") or option.get("value") or chr(97 + index))
            option_text = str(option.get("text") or option.get("label") or option.get("value") or option_id)
        else:
            option_id = chr(97 + index)
            option_text = str(option)
        normalized_options.append({"id": option_id, "text": option_text})
    return {"text": text, "options": normalized_options}


def _coerce_answer_key(raw: dict[str, Any], prompt: dict[str, Any]) -> dict[str, Any]:
    answer_key = raw.get("answer_key_json") or raw.get("answer_key")
    if isinstance(answer_key, dict):
        return answer_key

    correct = raw.get("correct_answer")
    option_ids = [str(option.get("id")) for option in prompt.get("options", []) if isinstance(option, dict)]
    if correct is not None:
        correct_text = str(correct)
        if correct_text in option_ids:
            return {"correct_option_id": correct_text}
        for option in prompt.get("options", []):
            if isinstance(option, dict) and str(option.get("text")) == correct_text:
                return {"correct_option_id": str(option["id"])}
    return {"correct_option_id": option_ids[0] if option_ids else "a"}


def _coerce_generated_question(raw: dict[str, Any], config: dict[str, Any], lesson_id: str) -> dict[str, Any]:
    question_type = QuestionType(raw.get("question_type") or raw.get("type") or config.get("question_type"))
    skill = SkillType(raw.get("skill") or config.get("skill"))
    prompt = _coerce_prompt(raw)
    explanation = raw.get("explanation_json") or raw.get("explanation") or {"text": "Generated by AI."}
    if isinstance(explanation, str):
        explanation = {"text": explanation}
    return {
        "lesson_id": lesson_id,
        "question_type": question_type,
        "skill": skill,
        "difficulty": int(raw.get("difficulty") or config.get("difficulty") or 1),
        "prompt_json": prompt,
        "answer_key_json": _coerce_answer_key(raw, prompt),
        "explanation_json": explanation,
    }


def _create_questions_from_ai_response(
    *,
    db,
    job: GenerationJob,
    lesson: Lesson,
    content: str,
    config: dict[str, Any],
) -> list[Question]:
    questions_data = json.loads(content)
    if not isinstance(questions_data, list):
        raise ValueError("AI response must be a JSON array of questions")

    created_questions = []
    for q_data in questions_data:
        if not isinstance(q_data, dict):
            continue

        materialized = _coerce_generated_question(q_data, config, lesson.id)
        validate_question_payload(
            question_type=materialized["question_type"],
            skill=materialized["skill"],
            difficulty=materialized["difficulty"],
            prompt_json=materialized["prompt_json"],
            answer_key_json=materialized["answer_key_json"],
            explanation_json=materialized["explanation_json"],
            audio_asset_id=None,
            require_explanation=True,
        )
        question = Question(
            lesson_id=materialized["lesson_id"],
            question_type=materialized["question_type"],
            skill=materialized["skill"],
            difficulty=materialized["difficulty"],
            prompt_json=materialized["prompt_json"],
            answer_key_json=materialized["answer_key_json"],
            explanation_json=materialized["explanation_json"],
            status=QuestionStatus.AUTO_VALIDATED,
            is_ai_generated=True,
            created_by=job.created_by,
        )
        db.add(question)
        db.flush()
        snapshot_question(db, question, actor_id=job.created_by)
        created_questions.append(question)
    return created_questions


@celery_app.task(bind=True, name="ai.generate_questions")
def generate_questions_task(self, job_id: str):
    start_time = time.time()
    db = SessionLocal()

    try:
        job = db.query(GenerationJob).filter(GenerationJob.id == job_id).first()
        if not job:
            return {"status": "error", "message": f"Job {job_id} not found"}

        if job.status == JobStatus.CANCELLED:
            return {"status": "cancelled", "message": "Job was cancelled"}

        job.status = JobStatus.PROCESSING
        job.started_at = datetime.now(timezone.utc)
        job.celery_task_id = self.request.id
        db.commit()

        lesson = db.query(Lesson).filter(Lesson.id == job.target_id).first() if job.target_id else None
        if lesson is None:
            raise ValueError("Lesson not found")

        config = _job_config(job)
        content, metadata = get_ai_provider().generate_questions(job.prompt_json)
        try:
            created_questions = _create_questions_from_ai_response(
                db=db,
                job=job,
                lesson=lesson,
                content=content,
                config=config,
            )
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"AI returned invalid JSON: {exc}\nResponse: {content}") from exc
        except (QuestionWorkflowError, ValueError) as exc:
            raise RuntimeError(f"Validation error: {exc}") from exc

        job.status = JobStatus.COMPLETED
        job.raw_response = content
        job.tokens_used = metadata.get("tokens_used", 0)
        job.completed_at = datetime.now(timezone.utc)
        job.error_message = None
        db.commit()
        return {
            "status": "success",
            "created_count": len(created_questions),
            "latency_seconds": time.time() - start_time,
        }

    except Exception as e:
        db.rollback()
        job = db.query(GenerationJob).filter(GenerationJob.id == job_id).first()
        if job:
            job.status = JobStatus.FAILED
            job.error_message = str(e)
            job.completed_at = datetime.now(timezone.utc)
            db.commit()
        return {"status": "error", "message": str(e)}
    finally:
        db.close()


@celery_app.task(bind=True, name="ai.generate_adaptive_evaluation")
def generate_adaptive_evaluation_task(self, job_id: str):
    start_time = time.time()
    db = SessionLocal()

    try:
        job = db.query(GenerationJob).filter(GenerationJob.id == job_id).first()
        if not job:
            return {"status": "error", "message": f"Job {job_id} not found"}

        if job.status == JobStatus.CANCELLED:
            return {"status": "cancelled", "message": "Job was cancelled"}

        job.status = JobStatus.PROCESSING
        job.started_at = datetime.now(timezone.utc)
        job.celery_task_id = self.request.id
        db.commit()

        lesson = db.query(Lesson).filter(Lesson.id == job.target_id).first() if job.target_id else None
        if lesson is None:
            raise ValueError("Lesson not found")

        vocab_context = ", ".join(v.word for v in lesson.vocabularies) or "Tidak ada batasan kosakata spesifik"
        kanji_context = ", ".join(k.character for k in lesson.kanjis) or "Tidak ada batasan kanji spesifik"
        grammar_context = (
            ", ".join(g.structure for g in lesson.grammar_points) or "Tidak ada batasan tata bahasa spesifik"
        )
        base_prompt = _job_config(job)
        count = base_prompt.get("question_count") or base_prompt.get("count") or 5
        base_prompt.setdefault("question_type", QuestionType.MULTIPLE_CHOICE.value)
        base_prompt.setdefault("skill", SkillType.VOCABULARY.value)

        rag_prompt = f"""
Kamu adalah AI Tutor JLPT dan Mesin Evaluasi Otomatis.
TUGAS: Evaluasi perkembangan belajar siswa pada materi ini dengan membuat kuis dinamis.

SYARAT MUTLAK (Data RAG):
Kamu HANYA BOLEH menggunakan kosakata, kanji, dan tata bahasa dari daftar kurikulum resmi
berikut ini untuk menyusun kuis:
- Vocab: {vocab_context}
- Kanji: {kanji_context}
- Grammar: {grammar_context}

INSTRUKSI: Buatkan {count} soal Multiple Choice tingkat N5 yang menargetkan materi di atas.
Keluarkan output HANYA dalam format JSON Array sesuai schema sistem.
        """

        content, metadata = get_ai_provider().generate_questions(rag_prompt)
        try:
            created_questions = _create_questions_from_ai_response(
                db=db,
                job=job,
                lesson=lesson,
                content=content,
                config=base_prompt,
            )
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"AI returned invalid JSON: {exc}\nResponse: {content}") from exc
        except (QuestionWorkflowError, ValueError) as exc:
            raise RuntimeError(f"Validation error: {exc}") from exc

        job.status = JobStatus.COMPLETED
        job.raw_response = content
        job.tokens_used = metadata.get("tokens_used", 0)
        job.completed_at = datetime.now(timezone.utc)
        job.error_message = None
        db.commit()
        return {
            "status": "success",
            "created_count": len(created_questions),
            "latency_seconds": time.time() - start_time,
        }

    except Exception as e:
        db.rollback()
        job = db.query(GenerationJob).filter(GenerationJob.id == job_id).first()
        if job:
            job.status = JobStatus.FAILED
            job.error_message = str(e)
            job.completed_at = datetime.now(timezone.utc)
            db.commit()
        return {"status": "error", "message": str(e)}
    finally:
        db.close()
