import json
import time
from datetime import datetime, timezone
from typing import Any

from app.db.session import SessionLocal
from app.models.ai_jobs import GenerationJob, JobStatus
from app.models.material import MaterialDocument
from app.models.question import Question, QuestionStatus, QuestionType, SkillType
from app.services.ai_provider import get_ai_provider
from app.services.question_workflow import QuestionWorkflowError, snapshot_question, validate_question_payload
from app.worker import celery_app


def _job_config(job: GenerationJob) -> dict[str, Any]:
    try:
        payload = json.loads(job.prompt_json)
        return payload if isinstance(payload, dict) else {}
    except json.JSONDecodeError:
        return {"additional_notes": job.prompt_json}


def _generation_prompt(config: dict[str, Any], raw_prompt: str) -> str:
    count = int(config.get("question_count") or config.get("count") or 5)
    question_type = config.get("question_type") or QuestionType.MULTIPLE_CHOICE.value
    skill = config.get("skill") or SkillType.READING.value
    difficulty = int(config.get("difficulty") or 1)
    notes = config.get("additional_notes") or "Tidak ada catatan tambahan."
    source_material = config.get("source_material")

    source_block = (
        f"SUMBER MATERI PDF:\n{source_material}"
        if source_material
        else f"KONFIGURASI JOB:\n{raw_prompt}"
    )
    return f"""
Kamu adalah pembuat soal bahasa Jepang untuk aplikasi kursus.

TUGAS:
Buat {count} soal berdasarkan sumber materi yang diberikan.

BATASAN:
- Gunakan hanya informasi dari sumber materi.
- Jangan membuat fakta baru di luar sumber materi.
- Level kesulitan: {difficulty}.
- Skill target: {skill}.
- Tipe soal utama: {question_type}.
- Catatan admin: {notes}

FORMAT OUTPUT:
Kembalikan HANYA JSON array. Setiap item harus berbentuk:
{{
  "question_type": "{question_type}",
  "skill": "{skill}",
  "difficulty": {difficulty},
  "prompt_json": {{
    "text": "teks pertanyaan",
    "options": [
      {{"id": "a", "text": "opsi A"}},
      {{"id": "b", "text": "opsi B"}},
      {{"id": "c", "text": "opsi C"}},
      {{"id": "d", "text": "opsi D"}}
    ]
  }},
  "answer_key_json": {{"correct_option_id": "a"}},
  "explanation_json": {{"text": "penjelasan singkat berdasarkan sumber materi"}}
}}

{source_block}
""".strip()


def _coerce_prompt(raw: dict[str, Any]) -> dict[str, Any]:
    prompt = raw.get("prompt_json") or raw.get("prompt")
    if isinstance(prompt, dict):
        return prompt

    text = str(prompt or raw.get("text") or raw.get("question") or "Generated question")
    options = raw.get("options")
    if not isinstance(options, list) or not options:
        options = ["A", "B"]

    normalized_options = []
    for index, option in enumerate(options):
        if isinstance(option, dict):
            option_id = str(option.get("id") or option.get("value") or chr(97 + index))
            option_text = str(option.get("text") or option.get("label") or option.get("value") or option_id)
        else:
            option_id = chr(97 + index)
            option_text = str(option)
        normalized_options.append({"id": option_id, "text": option_text})
    return {"text": text, "options": normalized_options}


def _coerce_answer_key(raw: dict[str, Any], prompt: dict[str, Any]) -> dict[str, Any]:
    answer_key = raw.get("answer_key_json") or raw.get("answer_key")
    if isinstance(answer_key, dict):
        return answer_key

    correct = raw.get("correct_answer")
    option_ids = [str(option.get("id")) for option in prompt.get("options", []) if isinstance(option, dict)]
    if correct is not None:
        correct_text = str(correct)
        if correct_text in option_ids:
            return {"correct_option_id": correct_text}
        for option in prompt.get("options", []):
            if isinstance(option, dict) and str(option.get("text")) == correct_text:
                return {"correct_option_id": str(option["id"])}
    return {"correct_option_id": option_ids[0] if option_ids else "a"}


def _coerce_generated_question(raw: dict[str, Any], config: dict[str, Any], material_id: str) -> dict[str, Any]:
    question_type = QuestionType(raw.get("question_type") or raw.get("type") or config.get("question_type"))
    skill = SkillType(raw.get("skill") or config.get("skill"))
    prompt = _coerce_prompt(raw)
    explanation = raw.get("explanation_json") or raw.get("explanation") or {"text": "Generated by AI."}
    if isinstance(explanation, str):
        explanation = {"text": explanation}
    return {
        "material_id": material_id,
        "question_type": question_type,
        "skill": skill,
        "difficulty": int(raw.get("difficulty") or config.get("difficulty") or 1),
        "prompt_json": prompt,
        "answer_key_json": _coerce_answer_key(raw, prompt),
        "explanation_json": explanation,
    }


def _create_questions_from_ai_response(
    *,
    db,
    job: GenerationJob,
    material: MaterialDocument,
    content: str,
    config: dict[str, Any],
) -> list[Question]:
    questions_data = json.loads(content)
    if not isinstance(questions_data, list):
        raise ValueError("AI response must be a JSON array of questions")

    created_questions = []
    for q_data in questions_data:
        if not isinstance(q_data, dict):
            continue

        materialized = _coerce_generated_question(q_data, config, material.id)
        validate_question_payload(
            question_type=materialized["question_type"],
            skill=materialized["skill"],
            difficulty=materialized["difficulty"],
            prompt_json=materialized["prompt_json"],
            answer_key_json=materialized["answer_key_json"],
            explanation_json=materialized["explanation_json"],
            require_explanation=True,
        )
        question = Question(
            material_id=materialized["material_id"],
            lesson_id=material.lesson_id,
            question_type=materialized["question_type"],
            skill=materialized["skill"],
            difficulty=materialized["difficulty"],
            prompt_json=materialized["prompt_json"],
            answer_key_json=materialized["answer_key_json"],
            explanation_json=materialized["explanation_json"],
            status=QuestionStatus.AUTO_VALIDATED,
            is_ai_generated=True,
            created_by=job.created_by,
        )
        db.add(question)
        db.flush()
        snapshot_question(db, question, actor_id=job.created_by)
        if config.get("auto_publish"):
            question.status = QuestionStatus.PUBLISHED
            question.published_at = datetime.now(timezone.utc)
            snapshot_question(db, question, actor_id=job.created_by)
        created_questions.append(question)
    return created_questions


@celery_app.task(bind=True, name="ai.generate_questions")
def generate_questions_task(self, job_id: str):
    start_time = time.time()
    db = SessionLocal()

    try:
        job = db.query(GenerationJob).filter(GenerationJob.id == job_id).first()
        if not job:
            return {"status": "error", "message": f"Job {job_id} not found"}

        if job.status == JobStatus.CANCELLED:
            return {"status": "cancelled", "message": "Job was cancelled"}

        job.status = JobStatus.PROCESSING
        job.started_at = datetime.now(timezone.utc)
        job.celery_task_id = self.request.id
        db.commit()

        material = db.query(MaterialDocument).filter(MaterialDocument.id == job.target_id).first() if job.target_id else None
        if material is None:
            raise ValueError("Material not found")

        config = _job_config(job)
        content, metadata = get_ai_provider().generate_questions(_generation_prompt(config, job.prompt_json))
        try:
            created_questions = _create_questions_from_ai_response(
                db=db,
                job=job,
                material=material,
                content=content,
                config=config,
            )
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"AI returned invalid JSON: {exc}\nResponse: {content}") from exc
        except (QuestionWorkflowError, ValueError) as exc:
            raise RuntimeError(f"Validation error: {exc}") from exc

        job.status = JobStatus.COMPLETED
        job.raw_response = json.dumps(
            {
                "ai_response": content,
                "created_question_ids": [question.id for question in created_questions],
            },
            ensure_ascii=False,
            separators=(",", ":"),
        )
        job.tokens_used = metadata.get("tokens_used", 0)
        job.completed_at = datetime.now(timezone.utc)
        job.error_message = None
        db.commit()
        return {
            "status": "success",
            "created_count": len(created_questions),
            "latency_seconds": time.time() - start_time,
        }

    except Exception as e:
        db.rollback()
        job = db.query(GenerationJob).filter(GenerationJob.id == job_id).first()
        if job:
            job.status = JobStatus.FAILED
            job.error_message = str(e)
            job.completed_at = datetime.now(timezone.utc)
            db.commit()
        return {"status": "error", "message": str(e)}
    finally:
        db.close()
