"""Add JLPT Simulation models

Revision ID: 69e963bb7b7b
Revises: 0d720c4e09f5
Create Date: 2026-07-11 10:45:29.104139

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69e963bb7b7b"
down_revision: Union[str, None] = "0d720c4e09f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jlpt_simulations",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("passing_score", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jlpt_simulations_id"), "jlpt_simulations", ["id"], unique=False)
    op.create_table(
        "jlpt_simulation_sections",
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("section_type", sa.String(length=50), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("passing_score", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["simulation_id"], ["jlpt_simulations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jlpt_simulation_sections_id"), "jlpt_simulation_sections", ["id"], unique=False)
    op.create_table(
        "user_simulation_attempts",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("total_score", sa.Integer(), nullable=True),
        sa.Column("is_passed", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["simulation_id"], ["jlpt_simulations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_simulation_attempts_id"), "user_simulation_attempts", ["id"], unique=False)
    op.create_table(
        "user_simulation_attempt_sections",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("section_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("is_passed", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["user_simulation_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["jlpt_simulation_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_simulation_attempt_sections_id"), "user_simulation_attempt_sections", ["id"], unique=False
    )
    op.create_table(
        "jlpt_simulation_questions",
        sa.Column("section_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["jlpt_simulation_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jlpt_simulation_questions_id"), "jlpt_simulation_questions", ["id"], unique=False)
    op.create_table(
        "user_simulation_attempt_questions",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_section_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("question_revision_id", sa.String(length=36), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("is_answered", sa.Boolean(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("answer_data_json", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["user_simulation_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["attempt_section_id"], ["user_simulation_attempt_sections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_revision_id"], ["question_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_simulation_attempt_questions_id"), "user_simulation_attempt_questions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_simulation_attempt_questions_id"), table_name="user_simulation_attempt_questions")
    op.drop_table("user_simulation_attempt_questions")
    op.drop_index(op.f("ix_jlpt_simulation_questions_id"), table_name="jlpt_simulation_questions")
    op.drop_table("jlpt_simulation_questions")
    op.drop_index(op.f("ix_user_simulation_attempt_sections_id"), table_name="user_simulation_attempt_sections")
    op.drop_table("user_simulation_attempt_sections")
    op.drop_index(op.f("ix_user_simulation_attempts_id"), table_name="user_simulation_attempts")
    op.drop_table("user_simulation_attempts")
    op.drop_index(op.f("ix_jlpt_simulation_sections_id"), table_name="jlpt_simulation_sections")
    op.drop_table("jlpt_simulation_sections")
    op.drop_index(op.f("ix_jlpt_simulations_id"), table_name="jlpt_simulations")
    op.drop_table("jlpt_simulations")
    # ### end Alembic commands ###
