"""Add IN_REVIEW to QuestionStatus

Revision ID: 4e806a9fd068
Revises: 25c9cb6ccbe3
Create Date: 2026-07-10 22:35:19.020105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e806a9fd068"
down_revision: Union[str, None] = "25c9cb6ccbe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question_reviews",
        "status_given",
        existing_type=mysql.ENUM(
            "DRAFT", "AUTO_VALIDATED", "NEEDS_REVISION", "APPROVED", "PUBLISHED", "REJECTED", "ARCHIVED"
        ),
        type_=sa.Enum(
            "DRAFT",
            "AUTO_VALIDATED",
            "IN_REVIEW",
            "NEEDS_REVISION",
            "APPROVED",
            "PUBLISHED",
            "REJECTED",
            "ARCHIVED",
            name="questionstatus",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "questions",
        "status",
        existing_type=mysql.ENUM(
            "DRAFT", "AUTO_VALIDATED", "NEEDS_REVISION", "APPROVED", "PUBLISHED", "REJECTED", "ARCHIVED"
        ),
        type_=sa.Enum(
            "DRAFT",
            "AUTO_VALIDATED",
            "IN_REVIEW",
            "NEEDS_REVISION",
            "APPROVED",
            "PUBLISHED",
            "REJECTED",
            "ARCHIVED",
            name="questionstatus",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions",
        "status",
        existing_type=sa.Enum(
            "DRAFT",
            "AUTO_VALIDATED",
            "IN_REVIEW",
            "NEEDS_REVISION",
            "APPROVED",
            "PUBLISHED",
            "REJECTED",
            "ARCHIVED",
            name="questionstatus",
        ),
        type_=mysql.ENUM("DRAFT", "AUTO_VALIDATED", "NEEDS_REVISION", "APPROVED", "PUBLISHED", "REJECTED", "ARCHIVED"),
        existing_nullable=False,
    )
    op.alter_column(
        "question_reviews",
        "status_given",
        existing_type=sa.Enum(
            "DRAFT",
            "AUTO_VALIDATED",
            "IN_REVIEW",
            "NEEDS_REVISION",
            "APPROVED",
            "PUBLISHED",
            "REJECTED",
            "ARCHIVED",
            name="questionstatus",
        ),
        type_=mysql.ENUM("DRAFT", "AUTO_VALIDATED", "NEEDS_REVISION", "APPROVED", "PUBLISHED", "REJECTED", "ARCHIVED"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
