"""Update learning_sessions

Revision ID: 922fc581d071
Revises: 4e806a9fd068
Create Date: 2026-07-10 22:53:37.810870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "922fc581d071"
down_revision: Union[str, None] = "4e806a9fd068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("learning_session_questions", sa.Column("question_revision_id", sa.String(length=36), nullable=False))
    op.alter_column(
        "learning_session_questions",
        "user_answer_json",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.create_foreign_key(
        None, "learning_session_questions", "question_revisions", ["question_revision_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "learning_session_questions", type_="foreignkey")
    op.alter_column(
        "learning_session_questions",
        "user_answer_json",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("learning_session_questions", "question_revision_id")
    # ### end Alembic commands ###
