"""add celery task id to generation jobs

Revision ID: 0d720c4e09f5
Revises: 922fc581d071
Create Date: 2026-07-11 09:15:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d720c4e09f5"
down_revision: Union[str, None] = "922fc581d071"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generation_jobs", sa.Column("celery_task_id", sa.String(length=255), nullable=True))
    op.add_column("generation_jobs", sa.Column("target_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_generation_jobs_celery_task_id"), "generation_jobs", ["celery_task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generation_jobs_celery_task_id"), table_name="generation_jobs")
    op.drop_column("generation_jobs", "target_id")
    op.drop_column("generation_jobs", "celery_task_id")
    # ### end Alembic commands ###
