"""Add missing columns

Revision ID: 648a99e418e5
Revises: 69e963bb7b7b
Create Date: 2026-07-11 19:20:19.780277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '648a99e418e5'
down_revision: Union[str, None] = '69e963bb7b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_verification_tokens_expires_at', 'email_verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index('ix_email_verification_tokens_user', 'email_verification_tokens', ['user_id', 'is_used'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index('ix_password_reset_tokens_user', 'password_reset_tokens', ['user_id', 'is_used'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=50), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'is_revoked', 'expires_at'], unique=False)
    op.drop_index(op.f('ix_refreshtokens_id'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_token_hash'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    op.drop_index(op.f('ix_passwordresettokens_id'), table_name='passwordresettokens')
    op.drop_index(op.f('ix_passwordresettokens_token_hash'), table_name='passwordresettokens')
    op.drop_table('passwordresettokens')
    op.add_column('audio_assets', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('audio_assets', sa.Column('storage_backend', sa.String(length=32), server_default='local', nullable=False))
    op.add_column('audio_assets', sa.Column('storage_key', sa.String(length=512), nullable=True))
    op.add_column('audio_assets', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('audio_assets', sa.Column('content_type', sa.String(length=100), server_default='audio/mpeg', nullable=False))
    op.add_column('audio_assets', sa.Column('file_size_bytes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('audio_assets', sa.Column('checksum', sa.String(length=64), nullable=True))
    op.add_column('audio_assets', sa.Column('translation', sa.Text(), nullable=True))
    op.add_column('audio_assets', sa.Column('transcript_visible', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('audio_assets', sa.Column('speaker', sa.String(length=100), nullable=True))
    op.add_column('audio_assets', sa.Column('source_type', sa.String(length=32), server_default='upload', nullable=False))
    op.add_column('audio_assets', sa.Column('provider', sa.String(length=64), nullable=True))
    op.add_column('audio_assets', sa.Column('level_id', sa.String(length=36), nullable=True))
    op.add_column('audio_assets', sa.Column('created_by_id', sa.String(length=36), nullable=True))
    op.add_column('audio_assets', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('audio_assets', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('audio_assets', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audio_assets', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('audio_assets', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('audio_assets', 'duration_seconds',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               nullable=False)
    op.create_index(op.f('ix_audio_assets_checksum'), 'audio_assets', ['checksum'], unique=True)
    op.create_index('ix_audio_assets_level_visibility', 'audio_assets', ['level_id', 'is_published', 'is_archived'], unique=False)
    op.create_index('ix_audio_assets_visibility', 'audio_assets', ['is_published', 'is_archived'], unique=False)
    op.create_foreign_key(None, 'audio_assets', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audio_assets', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.add_column('courses', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('courses', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('courses', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('courses', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('courses', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index('ix_courses_parent_visibility_sequence', 'courses', ['level_id', 'is_published', 'is_archived', 'sequence'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_unique_constraint('uq_courses_level_title', 'courses', ['level_id', 'title'])
    op.add_column('example_sentences', sa.Column('level_id', sa.String(length=36), nullable=True))
    op.add_column('example_sentences', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('example_sentences', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('example_sentences', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('example_sentences', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_example_sentences_level_visibility', 'example_sentences', ['level_id', 'is_published', 'is_archived'], unique=False)
    op.create_foreign_key(None, 'example_sentences', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.alter_column('generation_jobs', 'job_type',
               existing_type=mysql.ENUM('QUESTION_GENERATION', 'TTS_GENERATION'),
               type_=sa.Enum('QUESTION_GENERATION', 'TTS_GENERATION', 'ADAPTIVE_EVALUATION_GENERATION', name='jobtype'),
               existing_nullable=False)
    op.add_column('grammar_points', sa.Column('usage_notes', sa.Text(), nullable=True))
    op.add_column('grammar_points', sa.Column('level_id', sa.String(length=36), nullable=True))
    op.add_column('grammar_points', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('grammar_points', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('grammar_points', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('grammar_points', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('grammar_points', 'structure',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index('ix_grammar_points_level_visibility', 'grammar_points', ['level_id', 'is_published', 'is_archived'], unique=False)
    op.create_unique_constraint('uq_grammar_points_title_structure', 'grammar_points', ['title', 'structure'])
    op.create_foreign_key(None, 'grammar_points', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.create_index('uq_simulation_question', 'jlpt_simulation_questions', ['section_id', 'question_id'], unique=True)
    op.create_index('uq_simulation_question_order', 'jlpt_simulation_questions', ['section_id', 'order_number'], unique=True)
    op.drop_constraint(op.f('jlpt_simulation_questions_ibfk_1'), 'jlpt_simulation_questions', type_='foreignkey')
    op.create_foreign_key(None, 'jlpt_simulation_questions', 'questions', ['question_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('jlpt_simulation_sections', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('uq_simulation_section_sequence', 'jlpt_simulation_sections', ['simulation_id', 'sequence'], unique=True)
    op.add_column('jlpt_simulations', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('jlpt_simulations', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('jlpt_simulations', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index('ix_jlpt_simulations_level_published', 'jlpt_simulations', ['level', 'is_published', 'is_archived'], unique=False)
    op.add_column('kanjis', sa.Column('radical', sa.String(length=32), nullable=True))
    op.add_column('kanjis', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('kanjis', sa.Column('level_id', sa.String(length=36), nullable=True))
    op.add_column('kanjis', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('kanjis', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('kanjis', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('kanjis', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('kanjis', 'stroke_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('ix_kanjis_level_visibility', 'kanjis', ['level_id', 'is_published', 'is_archived'], unique=False)
    op.create_unique_constraint('uq_kanjis_character', 'kanjis', ['character'])
    op.create_foreign_key(None, 'kanjis', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.alter_column('learning_session_questions', 'is_answered',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('learning_session_questions', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('learning_session_questions', 'response_time_ms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('ix_session_questions_session_answered', 'learning_session_questions', ['session_id', 'is_answered'], unique=False)
    op.create_unique_constraint('uq_session_question', 'learning_session_questions', ['session_id', 'question_id'])
    op.create_unique_constraint('uq_session_question_order', 'learning_session_questions', ['session_id', 'order_number'])
    op.drop_constraint(op.f('learning_session_questions_ibfk_3'), 'learning_session_questions', type_='foreignkey')
    op.drop_constraint(op.f('learning_session_questions_ibfk_1'), 'learning_session_questions', type_='foreignkey')
    op.create_foreign_key(None, 'learning_session_questions', 'question_revisions', ['question_revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'learning_session_questions', 'questions', ['question_id'], ['id'], ondelete='RESTRICT')
    op.add_column('learning_sessions', sa.Column('source', sa.Enum('LESSON', 'REVIEW', 'MISTAKE', name='sessionsource'), nullable=False))
    op.add_column('learning_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('learning_sessions', sa.Column('progress_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('learning_sessions', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED'),
               type_=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='sessionstatus'),
               existing_nullable=False)
    op.alter_column('learning_sessions', 'total_questions',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('learning_sessions', 'answered_questions',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('learning_sessions', 'correct_answers',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('learning_sessions', 'final_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('learning_sessions', 'started_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index('ix_learning_sessions_user_status', 'learning_sessions', ['user_id', 'status', 'started_at'], unique=False)
    op.add_column('lesson_grammar_points', sa.Column('sequence', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lesson_kanjis', sa.Column('sequence', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lesson_sections', sa.Column('section_type', sa.String(length=32), server_default='article', nullable=False))
    op.add_column('lesson_sections', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('lesson_sections', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('lesson_sections', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lesson_sections', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('lesson_sections', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('ix_lesson_sections_parent_visibility_sequence', 'lesson_sections', ['lesson_id', 'is_published', 'is_archived', 'sequence'], unique=False)
    op.create_unique_constraint('uq_lesson_sections_lesson_sequence', 'lesson_sections', ['lesson_id', 'sequence'])
    op.add_column('lesson_vocabularies', sa.Column('sequence', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lessons', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('lessons', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('estimated_minutes', sa.Integer(), server_default='15', nullable=False))
    op.add_column('lessons', sa.Column('passing_score', sa.Integer(), server_default='70', nullable=False))
    op.add_column('lessons', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('lessons', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('lessons', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lessons', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index('ix_lessons_parent_visibility_sequence', 'lessons', ['unit_id', 'is_published', 'is_archived', 'sequence'], unique=False)
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    op.create_unique_constraint('uq_lessons_unit_title', 'lessons', ['unit_id', 'title'])
    op.add_column('levels', sa.Column('code', sa.String(length=16), nullable=True))
    op.add_column('levels', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('levels', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('levels', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('levels', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('levels', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index(op.f('ix_levels_code'), 'levels', ['code'], unique=True)
    op.create_index('ix_levels_visibility_sequence', 'levels', ['is_published', 'is_archived', 'sequence'], unique=False)
    op.create_index('ix_question_reviews_question_created', 'question_reviews', ['question_id', 'created_at'], unique=False)
    op.add_column('question_revisions', sa.Column('lesson_id', sa.String(length=36), nullable=False))
    op.add_column('question_revisions', sa.Column('reading_id', sa.String(length=36), nullable=True))
    op.add_column('question_revisions', sa.Column('audio_asset_id', sa.String(length=36), nullable=True))
    op.add_column('question_revisions', sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'CLOZE_MULTIPLE_CHOICE', 'TRUE_FALSE', 'MATCHING', 'ORDERING', 'KANJI_READING', 'READING_COMPREHENSION', 'LISTENING_MULTIPLE_CHOICE', 'LISTENING_TRUE_FALSE', 'LISTENING_WITH_IMAGE', name='questiontype'), nullable=False))
    op.add_column('question_revisions', sa.Column('skill', sa.Enum('VOCABULARY', 'GRAMMAR', 'READING', 'LISTENING', name='skilltype'), nullable=False))
    op.add_column('question_revisions', sa.Column('difficulty', sa.Integer(), nullable=False))
    op.alter_column('question_revisions', 'answer_key_json',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False)
    op.create_index('ix_question_revisions_question', 'question_revisions', ['question_id', 'version_number'], unique=False)
    op.create_unique_constraint('uq_question_revision_version', 'question_revisions', ['question_id', 'version_number'])
    op.add_column('questions', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('questions', 'question_type',
               existing_type=mysql.ENUM('MULTIPLE_CHOICE', 'TRUE_FALSE', 'MATCHING', 'ORDERING', 'CLOZE', 'LISTENING', 'READING'),
               type_=sa.Enum('MULTIPLE_CHOICE', 'CLOZE_MULTIPLE_CHOICE', 'TRUE_FALSE', 'MATCHING', 'ORDERING', 'KANJI_READING', 'READING_COMPREHENSION', 'LISTENING_MULTIPLE_CHOICE', 'LISTENING_TRUE_FALSE', 'LISTENING_WITH_IMAGE', name='questiontype'),
               existing_nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('questions', 'answer_key_json',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False)
    op.alter_column('questions', 'is_ai_generated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('questions', 'version_number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('ix_questions_selection', 'questions', ['lesson_id', 'status', 'skill', 'difficulty'], unique=False)
    op.create_index('ix_questions_status_updated', 'questions', ['status', 'updated_at'], unique=False)
    op.add_column('readings', sa.Column('furigana', sa.Text(), nullable=True))
    op.add_column('readings', sa.Column('difficulty', sa.Integer(), server_default='1', nullable=False))
    op.add_column('readings', sa.Column('sequence', sa.Integer(), server_default='0', nullable=False))
    op.add_column('readings', sa.Column('level_id', sa.String(length=36), nullable=True))
    op.add_column('readings', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('readings', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('readings', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('readings', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_readings_lesson_visibility_sequence', 'readings', ['lesson_id', 'is_published', 'is_archived', 'sequence'], unique=False)
    op.create_unique_constraint('uq_readings_lesson_title', 'readings', ['lesson_id', 'title'])
    op.create_foreign_key(None, 'readings', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.add_column('review_schedules', sa.Column('consecutive_correct', sa.Integer(), nullable=False))
    op.add_column('review_schedules', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('review_schedules', 'interval_days',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('ix_review_schedules_user_due', 'review_schedules', ['user_id', 'next_review_date'], unique=False)
    op.create_unique_constraint('uq_review_schedule_question', 'review_schedules', ['user_id', 'question_id'])
    op.add_column('units', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('units', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('units', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('units', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('units', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('units', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index('ix_units_parent_visibility_sequence', 'units', ['course_id', 'is_published', 'is_archived', 'sequence'], unique=False)
    op.create_index(op.f('ix_units_slug'), 'units', ['slug'], unique=True)
    op.create_unique_constraint('uq_units_course_title', 'units', ['course_id', 'title'])
    op.alter_column('user_lesson_progress', 'attempts_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_lesson_progress', 'best_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_lesson_progress', 'last_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('ix_lesson_progress_user_status', 'user_lesson_progress', ['user_id', 'status'], unique=False)
    op.create_unique_constraint('uq_user_lesson_progress', 'user_lesson_progress', ['user_id', 'lesson_id'])
    op.alter_column('user_masteries', 'mastery_level',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('ix_user_masteries_user_level', 'user_masteries', ['user_id', 'mastery_level'], unique=False)
    op.create_unique_constraint('uq_user_mastery_skill', 'user_masteries', ['user_id', 'skill'])
    op.add_column('user_mistakes', sa.Column('question_revision_id', sa.String(length=36), nullable=True))
    op.add_column('user_mistakes', sa.Column('last_succeeded_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_mistakes', 'mistake_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_mistakes', 'is_resolved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_mistakes', 'last_failed_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index('ix_user_mistakes_user_resolved', 'user_mistakes', ['user_id', 'is_resolved', 'last_failed_at'], unique=False)
    op.create_unique_constraint('uq_user_mistake_question', 'user_mistakes', ['user_id', 'question_id'])
    op.create_foreign_key(None, 'user_mistakes', 'question_revisions', ['question_revision_id'], ['id'], ondelete='SET NULL')
    op.add_column('user_simulation_attempt_questions', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.alter_column('user_simulation_attempt_questions', 'is_answered',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_simulation_attempt_questions', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_simulation_attempt_questions', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_simulation_attempt_questions', 'answer_data_json',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('uq_attempt_question', 'user_simulation_attempt_questions', ['attempt_section_id', 'question_id'], unique=True)
    op.create_index('uq_attempt_question_order', 'user_simulation_attempt_questions', ['attempt_section_id', 'order_number'], unique=True)
    op.drop_constraint(op.f('user_simulation_attempt_questions_ibfk_3'), 'user_simulation_attempt_questions', type_='foreignkey')
    op.drop_constraint(op.f('user_simulation_attempt_questions_ibfk_4'), 'user_simulation_attempt_questions', type_='foreignkey')
    op.create_foreign_key(None, 'user_simulation_attempt_questions', 'questions', ['question_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'user_simulation_attempt_questions', 'question_revisions', ['question_revision_id'], ['id'], ondelete='RESTRICT')
    op.add_column('user_simulation_attempt_sections', sa.Column('correct_count', sa.Integer(), nullable=False))
    op.add_column('user_simulation_attempt_sections', sa.Column('question_count', sa.Integer(), nullable=False))
    op.alter_column('user_simulation_attempt_sections', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_simulation_attempt_sections', 'is_passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index('uq_attempt_section', 'user_simulation_attempt_sections', ['attempt_id', 'section_id'], unique=True)
    op.drop_constraint(op.f('user_simulation_attempt_sections_ibfk_2'), 'user_simulation_attempt_sections', type_='foreignkey')
    op.create_foreign_key(None, 'user_simulation_attempt_sections', 'jlpt_simulation_sections', ['section_id'], ['id'], ondelete='RESTRICT')
    op.add_column('user_simulation_attempts', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_simulation_attempts', sa.Column('correct_count', sa.Integer(), nullable=False))
    op.add_column('user_simulation_attempts', sa.Column('question_count', sa.Integer(), nullable=False))
    op.alter_column('user_simulation_attempts', 'total_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_simulation_attempts', 'is_passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index('ix_simulation_attempt_simulation', 'user_simulation_attempts', ['simulation_id', 'created_at'], unique=False)
    op.create_index('ix_simulation_attempt_user_status', 'user_simulation_attempts', ['user_id', 'status'], unique=False)
    op.drop_constraint(op.f('user_simulation_attempts_ibfk_1'), 'user_simulation_attempts', type_='foreignkey')
    op.drop_constraint(op.f('user_simulation_attempts_ibfk_2'), 'user_simulation_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'user_simulation_attempts', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'user_simulation_attempts', 'jlpt_simulations', ['simulation_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'timezone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'target_level',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('LEARNER', 'CONTENT_EDITOR', 'REVIEWER', 'ADMINISTRATOR'),
               type_=sa.Enum('learner', 'content_editor', 'reviewer', 'administrator', name='user_role', native_enum=False, create_constraint=True, length=32),
               existing_nullable=False)
    op.alter_column('users', 'current_streak',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('users', 'longest_streak',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('vocabularies', sa.Column('part_of_speech', sa.String(length=64), nullable=True))
    op.add_column('vocabularies', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('vocabularies', sa.Column('level_id', sa.String(length=36), nullable=True))
    op.add_column('vocabularies', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('vocabularies', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('vocabularies', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vocabularies', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_vocabularies_level_visibility', 'vocabularies', ['level_id', 'is_published', 'is_archived'], unique=False)
    op.create_unique_constraint('uq_vocabularies_word_kana', 'vocabularies', ['word', 'kana'])
    op.create_foreign_key(None, 'vocabularies', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.alter_column('xp_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index('ix_xp_transactions_user_created', 'xp_transactions', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_xp_transaction_session', 'xp_transactions', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_xp_transaction_session', 'xp_transactions', type_='unique')
    op.drop_index('ix_xp_transactions_user_created', table_name='xp_transactions')
    op.alter_column('xp_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'vocabularies', type_='foreignkey')
    op.drop_constraint('uq_vocabularies_word_kana', 'vocabularies', type_='unique')
    op.drop_index('ix_vocabularies_level_visibility', table_name='vocabularies')
    op.drop_column('vocabularies', 'archived_at')
    op.drop_column('vocabularies', 'published_at')
    op.drop_column('vocabularies', 'is_archived')
    op.drop_column('vocabularies', 'is_published')
    op.drop_column('vocabularies', 'level_id')
    op.drop_column('vocabularies', 'notes')
    op.drop_column('vocabularies', 'part_of_speech')
    op.alter_column('users', 'longest_streak',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'current_streak',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('learner', 'content_editor', 'reviewer', 'administrator', name='user_role', native_enum=False, create_constraint=True, length=32),
               type_=mysql.ENUM('LEARNER', 'CONTENT_EDITOR', 'REVIEWER', 'ADMINISTRATOR'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'target_level',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'deactivated_at')
    op.drop_constraint(None, 'user_simulation_attempts', type_='foreignkey')
    op.drop_constraint(None, 'user_simulation_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('user_simulation_attempts_ibfk_2'), 'user_simulation_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_simulation_attempts_ibfk_1'), 'user_simulation_attempts', 'jlpt_simulations', ['simulation_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_simulation_attempt_user_status', table_name='user_simulation_attempts')
    op.drop_index('ix_simulation_attempt_simulation', table_name='user_simulation_attempts')
    op.alter_column('user_simulation_attempts', 'is_passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_simulation_attempts', 'total_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('user_simulation_attempts', 'question_count')
    op.drop_column('user_simulation_attempts', 'correct_count')
    op.drop_column('user_simulation_attempts', 'cancelled_at')
    op.drop_constraint(None, 'user_simulation_attempt_sections', type_='foreignkey')
    op.create_foreign_key(op.f('user_simulation_attempt_sections_ibfk_2'), 'user_simulation_attempt_sections', 'jlpt_simulation_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_attempt_section', table_name='user_simulation_attempt_sections')
    op.alter_column('user_simulation_attempt_sections', 'is_passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_simulation_attempt_sections', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('user_simulation_attempt_sections', 'question_count')
    op.drop_column('user_simulation_attempt_sections', 'correct_count')
    op.drop_constraint(None, 'user_simulation_attempt_questions', type_='foreignkey')
    op.drop_constraint(None, 'user_simulation_attempt_questions', type_='foreignkey')
    op.create_foreign_key(op.f('user_simulation_attempt_questions_ibfk_4'), 'user_simulation_attempt_questions', 'question_revisions', ['question_revision_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_simulation_attempt_questions_ibfk_3'), 'user_simulation_attempt_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_attempt_question_order', table_name='user_simulation_attempt_questions')
    op.drop_index('uq_attempt_question', table_name='user_simulation_attempt_questions')
    op.alter_column('user_simulation_attempt_questions', 'answer_data_json',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
    op.alter_column('user_simulation_attempt_questions', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_simulation_attempt_questions', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_simulation_attempt_questions', 'is_answered',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('user_simulation_attempt_questions', 'response_time_ms')
    op.drop_constraint(None, 'user_mistakes', type_='foreignkey')
    op.drop_constraint('uq_user_mistake_question', 'user_mistakes', type_='unique')
    op.drop_index('ix_user_mistakes_user_resolved', table_name='user_mistakes')
    op.alter_column('user_mistakes', 'last_failed_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_mistakes', 'is_resolved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_mistakes', 'mistake_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('user_mistakes', 'last_succeeded_at')
    op.drop_column('user_mistakes', 'question_revision_id')
    op.drop_constraint('uq_user_mastery_skill', 'user_masteries', type_='unique')
    op.drop_index('ix_user_masteries_user_level', table_name='user_masteries')
    op.alter_column('user_masteries', 'mastery_level',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('uq_user_lesson_progress', 'user_lesson_progress', type_='unique')
    op.drop_index('ix_lesson_progress_user_status', table_name='user_lesson_progress')
    op.alter_column('user_lesson_progress', 'last_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_lesson_progress', 'best_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_lesson_progress', 'attempts_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('uq_units_course_title', 'units', type_='unique')
    op.drop_index(op.f('ix_units_slug'), table_name='units')
    op.drop_index('ix_units_parent_visibility_sequence', table_name='units')
    op.alter_column('units', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('units', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('units', 'archived_at')
    op.drop_column('units', 'published_at')
    op.drop_column('units', 'is_archived')
    op.drop_column('units', 'slug')
    op.drop_constraint('uq_review_schedule_question', 'review_schedules', type_='unique')
    op.drop_index('ix_review_schedules_user_due', table_name='review_schedules')
    op.alter_column('review_schedules', 'interval_days',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('review_schedules', 'last_reviewed_at')
    op.drop_column('review_schedules', 'consecutive_correct')
    op.drop_constraint(None, 'readings', type_='foreignkey')
    op.drop_constraint('uq_readings_lesson_title', 'readings', type_='unique')
    op.drop_index('ix_readings_lesson_visibility_sequence', table_name='readings')
    op.drop_column('readings', 'archived_at')
    op.drop_column('readings', 'published_at')
    op.drop_column('readings', 'is_archived')
    op.drop_column('readings', 'is_published')
    op.drop_column('readings', 'level_id')
    op.drop_column('readings', 'sequence')
    op.drop_column('readings', 'difficulty')
    op.drop_column('readings', 'furigana')
    op.drop_index('ix_questions_status_updated', table_name='questions')
    op.drop_index('ix_questions_selection', table_name='questions')
    op.alter_column('questions', 'version_number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('questions', 'is_ai_generated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('questions', 'answer_key_json',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=sa.Enum('MULTIPLE_CHOICE', 'CLOZE_MULTIPLE_CHOICE', 'TRUE_FALSE', 'MATCHING', 'ORDERING', 'KANJI_READING', 'READING_COMPREHENSION', 'LISTENING_MULTIPLE_CHOICE', 'LISTENING_TRUE_FALSE', 'LISTENING_WITH_IMAGE', name='questiontype'),
               type_=mysql.ENUM('MULTIPLE_CHOICE', 'TRUE_FALSE', 'MATCHING', 'ORDERING', 'CLOZE', 'LISTENING', 'READING'),
               existing_nullable=False)
    op.drop_column('questions', 'published_at')
    op.drop_constraint('uq_question_revision_version', 'question_revisions', type_='unique')
    op.drop_index('ix_question_revisions_question', table_name='question_revisions')
    op.alter_column('question_revisions', 'answer_key_json',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True)
    op.drop_column('question_revisions', 'difficulty')
    op.drop_column('question_revisions', 'skill')
    op.drop_column('question_revisions', 'question_type')
    op.drop_column('question_revisions', 'audio_asset_id')
    op.drop_column('question_revisions', 'reading_id')
    op.drop_column('question_revisions', 'lesson_id')
    op.drop_index('ix_question_reviews_question_created', table_name='question_reviews')
    op.drop_index('ix_levels_visibility_sequence', table_name='levels')
    op.drop_index(op.f('ix_levels_code'), table_name='levels')
    op.alter_column('levels', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('levels', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('levels', 'archived_at')
    op.drop_column('levels', 'published_at')
    op.drop_column('levels', 'is_archived')
    op.drop_column('levels', 'code')
    op.drop_constraint('uq_lessons_unit_title', 'lessons', type_='unique')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_index('ix_lessons_parent_visibility_sequence', table_name='lessons')
    op.alter_column('lessons', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('lessons', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('lessons', 'archived_at')
    op.drop_column('lessons', 'published_at')
    op.drop_column('lessons', 'is_archived')
    op.drop_column('lessons', 'passing_score')
    op.drop_column('lessons', 'estimated_minutes')
    op.drop_column('lessons', 'summary')
    op.drop_column('lessons', 'slug')
    op.drop_column('lesson_vocabularies', 'sequence')
    op.drop_constraint('uq_lesson_sections_lesson_sequence', 'lesson_sections', type_='unique')
    op.drop_index('ix_lesson_sections_parent_visibility_sequence', table_name='lesson_sections')
    op.alter_column('lesson_sections', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('lesson_sections', 'archived_at')
    op.drop_column('lesson_sections', 'published_at')
    op.drop_column('lesson_sections', 'is_archived')
    op.drop_column('lesson_sections', 'is_published')
    op.drop_column('lesson_sections', 'section_type')
    op.drop_column('lesson_kanjis', 'sequence')
    op.drop_column('lesson_grammar_points', 'sequence')
    op.drop_index('ix_learning_sessions_user_status', table_name='learning_sessions')
    op.alter_column('learning_sessions', 'started_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('learning_sessions', 'final_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('learning_sessions', 'correct_answers',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('learning_sessions', 'answered_questions',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('learning_sessions', 'total_questions',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('learning_sessions', 'status',
               existing_type=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='sessionstatus'),
               type_=mysql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED'),
               existing_nullable=False)
    op.drop_column('learning_sessions', 'progress_processed_at')
    op.drop_column('learning_sessions', 'expires_at')
    op.drop_column('learning_sessions', 'source')
    op.drop_constraint(None, 'learning_session_questions', type_='foreignkey')
    op.drop_constraint(None, 'learning_session_questions', type_='foreignkey')
    op.create_foreign_key(op.f('learning_session_questions_ibfk_1'), 'learning_session_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('learning_session_questions_ibfk_3'), 'learning_session_questions', 'question_revisions', ['question_revision_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_session_question_order', 'learning_session_questions', type_='unique')
    op.drop_constraint('uq_session_question', 'learning_session_questions', type_='unique')
    op.drop_index('ix_session_questions_session_answered', table_name='learning_session_questions')
    op.alter_column('learning_session_questions', 'response_time_ms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('learning_session_questions', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('learning_session_questions', 'is_answered',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_constraint(None, 'kanjis', type_='foreignkey')
    op.drop_constraint('uq_kanjis_character', 'kanjis', type_='unique')
    op.drop_index('ix_kanjis_level_visibility', table_name='kanjis')
    op.alter_column('kanjis', 'stroke_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('kanjis', 'archived_at')
    op.drop_column('kanjis', 'published_at')
    op.drop_column('kanjis', 'is_archived')
    op.drop_column('kanjis', 'is_published')
    op.drop_column('kanjis', 'level_id')
    op.drop_column('kanjis', 'notes')
    op.drop_column('kanjis', 'radical')
    op.drop_index('ix_jlpt_simulations_level_published', table_name='jlpt_simulations')
    op.alter_column('jlpt_simulations', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('jlpt_simulations', 'published_at')
    op.drop_column('jlpt_simulations', 'is_archived')
    op.drop_index('uq_simulation_section_sequence', table_name='jlpt_simulation_sections')
    op.alter_column('jlpt_simulation_sections', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'jlpt_simulation_questions', type_='foreignkey')
    op.create_foreign_key(op.f('jlpt_simulation_questions_ibfk_1'), 'jlpt_simulation_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_simulation_question_order', table_name='jlpt_simulation_questions')
    op.drop_index('uq_simulation_question', table_name='jlpt_simulation_questions')
    op.drop_constraint(None, 'grammar_points', type_='foreignkey')
    op.drop_constraint('uq_grammar_points_title_structure', 'grammar_points', type_='unique')
    op.drop_index('ix_grammar_points_level_visibility', table_name='grammar_points')
    op.alter_column('grammar_points', 'structure',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_column('grammar_points', 'archived_at')
    op.drop_column('grammar_points', 'published_at')
    op.drop_column('grammar_points', 'is_archived')
    op.drop_column('grammar_points', 'is_published')
    op.drop_column('grammar_points', 'level_id')
    op.drop_column('grammar_points', 'usage_notes')
    op.alter_column('generation_jobs', 'job_type',
               existing_type=sa.Enum('QUESTION_GENERATION', 'TTS_GENERATION', 'ADAPTIVE_EVALUATION_GENERATION', name='jobtype'),
               type_=mysql.ENUM('QUESTION_GENERATION', 'TTS_GENERATION'),
               existing_nullable=False)
    op.drop_constraint(None, 'example_sentences', type_='foreignkey')
    op.drop_index('ix_example_sentences_level_visibility', table_name='example_sentences')
    op.drop_column('example_sentences', 'archived_at')
    op.drop_column('example_sentences', 'published_at')
    op.drop_column('example_sentences', 'is_archived')
    op.drop_column('example_sentences', 'is_published')
    op.drop_column('example_sentences', 'level_id')
    op.drop_constraint('uq_courses_level_title', 'courses', type_='unique')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index('ix_courses_parent_visibility_sequence', table_name='courses')
    op.alter_column('courses', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('courses', 'sequence',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('courses', 'archived_at')
    op.drop_column('courses', 'published_at')
    op.drop_column('courses', 'is_archived')
    op.drop_column('courses', 'image_url')
    op.drop_column('courses', 'slug')
    op.drop_constraint(None, 'audio_assets', type_='foreignkey')
    op.drop_constraint(None, 'audio_assets', type_='foreignkey')
    op.drop_index('ix_audio_assets_visibility', table_name='audio_assets')
    op.drop_index('ix_audio_assets_level_visibility', table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_checksum'), table_name='audio_assets')
    op.alter_column('audio_assets', 'duration_seconds',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('audio_assets', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.drop_column('audio_assets', 'archived_at')
    op.drop_column('audio_assets', 'published_at')
    op.drop_column('audio_assets', 'is_archived')
    op.drop_column('audio_assets', 'is_published')
    op.drop_column('audio_assets', 'created_by_id')
    op.drop_column('audio_assets', 'level_id')
    op.drop_column('audio_assets', 'provider')
    op.drop_column('audio_assets', 'source_type')
    op.drop_column('audio_assets', 'speaker')
    op.drop_column('audio_assets', 'transcript_visible')
    op.drop_column('audio_assets', 'translation')
    op.drop_column('audio_assets', 'checksum')
    op.drop_column('audio_assets', 'file_size_bytes')
    op.drop_column('audio_assets', 'content_type')
    op.drop_column('audio_assets', 'original_filename')
    op.drop_column('audio_assets', 'storage_key')
    op.drop_column('audio_assets', 'storage_backend')
    op.drop_column('audio_assets', 'title')
    op.create_table('passwordresettokens',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('passwordresettokens_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_passwordresettokens_token_hash'), 'passwordresettokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_passwordresettokens_id'), 'passwordresettokens', ['id'], unique=False)
    op.create_table('refreshtokens',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('device_info', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refreshtokens_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_refreshtokens_token_hash'), 'refreshtokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refreshtokens_id'), 'refreshtokens', ['id'], unique=False)
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_password_reset_tokens_user', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_expires_at', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_email_verification_tokens_user', table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_index('ix_email_verification_tokens_expires_at', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
